# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.5
#
# <auto-generated>
#
# Generated from file `Codetest.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module Codetest
_M_Codetest = Ice.openModule('Codetest')
__name__ = 'Codetest'

_M_Codetest._t_Health = IcePy.defineValue('::Codetest::Health', Ice.Value, -1, (), False, True, None, ())

if 'HealthPrx' not in _M_Codetest.__dict__:
    _M_Codetest.HealthPrx = Ice.createTempClass()
    class HealthPrx(Ice.ObjectPrx):

        def GetWallclockTime(self, context=None):
            return _M_Codetest.Health._op_GetWallclockTime.invoke(self, ((), context))

        def GetWallclockTimeAsync(self, context=None):
            return _M_Codetest.Health._op_GetWallclockTime.invokeAsync(self, ((), context))

        def begin_GetWallclockTime(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_Codetest.Health._op_GetWallclockTime.begin(self, ((), _response, _ex, _sent, context))

        def end_GetWallclockTime(self, _r):
            return _M_Codetest.Health._op_GetWallclockTime.end(self, _r)

        def GetFreeMemory(self, context=None):
            return _M_Codetest.Health._op_GetFreeMemory.invoke(self, ((), context))

        def GetFreeMemoryAsync(self, context=None):
            return _M_Codetest.Health._op_GetFreeMemory.invokeAsync(self, ((), context))

        def begin_GetFreeMemory(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_Codetest.Health._op_GetFreeMemory.begin(self, ((), _response, _ex, _sent, context))

        def end_GetFreeMemory(self, _r):
            return _M_Codetest.Health._op_GetFreeMemory.end(self, _r)

        def GetResponse(self, context=None):
            return _M_Codetest.Health._op_GetResponse.invoke(self, ((), context))

        def GetResponseAsync(self, context=None):
            return _M_Codetest.Health._op_GetResponse.invokeAsync(self, ((), context))

        def begin_GetResponse(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_Codetest.Health._op_GetResponse.begin(self, ((), _response, _ex, _sent, context))

        def end_GetResponse(self, _r):
            return _M_Codetest.Health._op_GetResponse.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Codetest.HealthPrx.ice_checkedCast(proxy, '::Codetest::Health', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Codetest.HealthPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Codetest::Health'
    _M_Codetest._t_HealthPrx = IcePy.defineProxy('::Codetest::Health', HealthPrx)

    _M_Codetest.HealthPrx = HealthPrx
    del HealthPrx

    _M_Codetest.Health = Ice.createTempClass()
    class Health(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Codetest::Health', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Codetest::Health'

        @staticmethod
        def ice_staticId():
            return '::Codetest::Health'

        def GetWallclockTime(self, current=None):
            raise NotImplementedError("servant method 'GetWallclockTime' not implemented")

        def GetFreeMemory(self, current=None):
            raise NotImplementedError("servant method 'GetFreeMemory' not implemented")

        def GetResponse(self, current=None):
            raise NotImplementedError("servant method 'GetResponse' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Codetest._t_HealthDisp)

        __repr__ = __str__

    _M_Codetest._t_HealthDisp = IcePy.defineClass('::Codetest::Health', Health, (), None, ())
    Health._ice_type = _M_Codetest._t_HealthDisp

    Health._op_GetWallclockTime = IcePy.Operation('GetWallclockTime', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_double, False, 0), ())
    Health._op_GetFreeMemory = IcePy.Operation('GetFreeMemory', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_long, False, 0), ())
    Health._op_GetResponse = IcePy.Operation('GetResponse', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())

    _M_Codetest.Health = Health
    del Health

# End of module Codetest
